"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&o8%rb&fvc#nkt@wpdnb!l4qn$oudv(mc6en_xx%p^80prk=!)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'tunnels.apps.TunnelsConfig',
    'api.apps.ApiConfig',
    'web.apps.WebConfig',
    'webpages.apps.WebpagesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # <-- required for browsable API
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CloudAtHome API',
    'DESCRIPTION': 'REST API for managing SSH tunnels and HAProxy forwarding rules.',
    'VERSION': '1.0.0',
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cloud-at-home settings

CAH_PUBLIC_KEY_STORAGE_PATH = '/var/tunnelagent/public_keys'
CAH_SSH_PORT = int(os.environ.get('CAH_SSH_PORT', '8022'))

HAPROXY_ENABLED = False
HAPROXY_API_HOST = 'localhost'
HAPROXY_API_PORT = int(os.environ.get('HAPROXY_API_PORT', '9999'))

# The standard HTTP/HTTPS ports this instance's HAProxy listens on. Configurable
# (rather than hardcoded 80/443) so more than one CloudAtHome instance can run on
# the same host -- see CAH_HTTP_PORT/CAH_HTTPS_PORT in .env.example. Also the
# port CAH_HOSTNAME (below) itself is reached on, so it must always match
# whatever haproxy.cfg actually binds for this instance.
CAH_HTTP_PORT = int(os.environ.get('CAH_HTTP_PORT', '80'))
CAH_HTTPS_PORT = int(os.environ.get('CAH_HTTPS_PORT', '443'))

# Required (in the docker-composed stack -- see reconcile_admin_route) hostname
# this instance's own Django (admin/API/web UI) answers on, routed through
# HAProxy's existing Host/SNI-based maps (see
# tunnels.management.commands.reconcile_admin_route) -- the only way to reach
# Django, there's no separate published port. Reachable over both HTTP and
# HTTPS, at CAH_HTTP_PORT/CAH_HTTPS_PORT, since Django terminates its own HTTPS
# via gunicorn (see docker/django/entrypoint.sh). Left unset here for local,
# non-Docker dev (manage.py runserver), where this whole mechanism doesn't
# apply. Reserved against home base-domain collisions in
# BaseDomainService.validate.
CAH_HOSTNAME = os.environ.get('CAH_HOSTNAME', '').strip().lower() or None

# Django rejects any request whose Host header isn't in ALLOWED_HOSTS
# regardless of DEBUG, so CAH_HOSTNAME must be added here -- otherwise every
# request routed to it through HAProxy 400s with DisallowedHost before ever
# reaching a view.
if CAH_HOSTNAME:
    ALLOWED_HOSTS.append(CAH_HOSTNAME)


def _parse_port_range(env_var, default):
    lo, hi = os.environ.get(env_var, default).split('-')
    return int(lo), int(hi) - int(lo) + 1


HTTP_INBOUND_PORT_RANGE = _parse_port_range('HTTP_INBOUND_PORT_RANGE', '8080-8180')
HTTPS_INBOUND_PORT_RANGE = _parse_port_range('HTTPS_INBOUND_PORT_RANGE', '8443-8543')

# The default `public_port` a home's HTTP/HTTPS mapping gets when it omits one
# (tunnels.services.DEFAULT_SCHEME_PORTS) -- independent of CAH_HTTP_PORT/
# CAH_HTTPS_PORT above, which are this instance's own standard port (and
# CAH_HOSTNAME's). The two happen to coincide by default, but don't have to:
# e.g. an operator running a second instance on the same host might move
# CAH_HTTP_PORT to a non-standard value for that reason alone, while still
# wanting homes to default to public_port 80 -- these being separate settings
# means that no longer drags the home-mapping default along with it. Gets its
# own haproxy.cfg bind line (HTTP_INBOUND_DEFAULT_PORT/HTTPS_INBOUND_DEFAULT_PORT),
# so it doesn't need to land on an already-bound port either -- HAProxy enables
# SO_REUSEPORT on its listeners by default, so bind lines are free to overlap
# in value with CAH_HTTP_PORT/CAH_HTTPS_PORT or with the inbound range below
# without conflict (verified: see haproxy_frontend_ports_and_reload notes in
# the project docs/memory).
HTTP_INBOUND_DEFAULT_PORT = int(os.environ.get('HTTP_INBOUND_DEFAULT_PORT') or CAH_HTTP_PORT)
HTTPS_INBOUND_DEFAULT_PORT = int(os.environ.get('HTTPS_INBOUND_DEFAULT_PORT') or CAH_HTTPS_PORT)

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/dashboard/'
LOGOUT_REDIRECT_URL = '/'