# Generated by Django 5.2.7 on 2026-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_delete_proxymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bandwidth_limit_kbps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
