# Generated by Django 5.2.7 on 2026-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_rename_local_port_to_tunnel_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxymapping',
            name='scheme',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=5),
        ),
    ]
