# Generated by Django 5.2.7 on 2026-07-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_homebasedomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebasedomain',
            options={'verbose_name_plural': 'Base domains'},
        ),
    ]
